name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: gyunseo/analyze-ur-youtube-backend
          stage: main
          yaml: |
            name: analyze-ur-youtube-backend
            app: python@3.11
            options:
              env:
                - name: OPENAI_API_KEY
                  secret: OPENAI_API_KEY
                - name: YOUTUBE_API_KEY
                  secret: YOUTUBE_API_KEY
              ports: 8000
              start: uvicorn main:app --host=0.0.0.0 --port=8000 --log-level=debug
              install: pip install -r requirements.txt
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
